# Generated by Django 5.2.6 on 2025-09-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creative',
            name='final_approval',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
