# Generated by Django 5.2.6 on 2025-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0002_creative_brand_alter_creative_final_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='posting_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
