# Generated by Django 5.2.6 on 2025-09-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0003_alter_creative_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='posting_date',
            field=models.DateField(),
        ),
    ]
